### ISSUE TITLE
Weird behaviour with GrabToPointerTip and MoveTransformGrabAttach

### ISSUE THREAD

**Issue by finartist** [thestonefox/VRTK#1911]
* Source of VRTK: Github
 * Version of VRTK: master 80db756d9f0a653236e3ff6f0ce4516ea1581111
 * Version of Unity3D: Unity 2017.3.1f1
 * Hardware used: Vive, also happens in Simulator
 * SDK used: SteamVR

### Steps to reproduce
- Setup a scene with one controller that has Interact Touch, Interact Grab and a Pointer script, and an object that has an Interactable Object and MoveTransformGrabAttach script
- check Grab To Pointer Tip in the Pointer script and IsGrabable in the Interactable Object
- check Precision Grab in MoveTransformGrabAttach

- on starting the scene, activate the pointer once and disable it while it points into the nothingness of the scene
- grab the object with the controller and rotate the controller

-> do this again but this time deactivate the pointer while the ray is short (eg point it at the object while standing close)

Edit: Hold To Activate has to be disabled on the pointer for the error to occur.

### Expected behavior
the object moves the always with the controller regardless of what happened with the pointer beforehand

### Current behavior
object movement is dependent on how long the pointer ray was before it was deactivated
(see https://drive.google.com/open?id=17CbQzzgljJfdInH4ZLi_jlV2DXmqt5uJ for a video example)

**Comment by finartist** [comment]
For some reason the ToggleObjectInteraction in VRTK_BasePointerRenderer is called twice, so the savedAttachPoint is set to the Pointer Tip on the second call. BUT when the Debugger is running it is only called once.

**Comment by finartist** [comment]
So, here is the Stacktrace for the first call:
```
at VRTK.VRTK_BasePointerRenderer.ToggleObjectInteraction(Boolean state)
   at VRTK.VRTK_BasePointerRenderer.ToggleInteraction(Boolean state)
   at VRTK.VRTK_BasePointerRenderer.Toggle(Boolean pointerState, Boolean actualState)
   at VRTK.VRTK_Pointer.Toggle(Boolean state)
   at VRTK.VRTK_Pointer.PointerActivated()
   at VRTK.VRTK_Pointer.DoActivationButtonPressed(System.Object sender, ControllerInteractionEventArgs e)
   at VRTK.VRTK_ControllerEvents.OnTouchpadTouchStart(ControllerInteractionEventArgs e)
   at VRTK.VRTK_ControllerEvents.CheckTouchpadEvents(VRTK.VRTK_ControllerReference controllerReference)
   at VRTK.VRTK_ControllerEvents.Update()
```

and for the second call:
```
 at VRTK.VRTK_BasePointerRenderer.ToggleObjectInteraction(Boolean state)
   at VRTK.VRTK_BasePointerRenderer.ToggleInteraction(Boolean state)
   at VRTK.VRTK_BasePointerRenderer.Toggle(Boolean pointerState, Boolean actualState)
   at VRTK.VRTK_Pointer.Toggle(Boolean state)
   at VRTK.VRTK_Pointer.PointerDeactivated()
   at VRTK.VRTK_Pointer.DoActivationButtonReleased(System.Object sender, ControllerInteractionEventArgs e)
   at VRTK.VRTK_ControllerEvents.OnTouchpadTouchEnd(ControllerInteractionEventArgs e)
   at VRTK.VRTK_ControllerEvents.CheckTouchpadEvents(VRTK.VRTK_ControllerReference controllerReference)
   at VRTK.VRTK_ControllerEvents.Update()
```

The second time is the result of releasing the activation button, but the pointer not being activated. This explains why it does not occur when a breakpoint is hit because the release of the button is not registered.
